import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Create a simple dataset (word and profanity level)
# Word and profanity levels: 0 = Non-profane, 1 = Mild, 2 = Profane
data = {
    'word': [
  "2 girls 1 cup",
  "2g1c",
  "4r5e",
  "5h1t",
  "5hit",
  "5ht",
  "@$$",
  "a s s",
  "a s shole",
  "a55",
  "a55hole",
  "a_s_s",
  "abbo",
  "abeed",
  "abuse",
  "acrotomophilia",
  "africoon",
  "ahole",
  "alabama hot pocket",
  "alaskan pipeline",
  "alligator bait",
  "alligatorbait",
  "amcik",
  "anal",
  "analannie",
  "analprobe",
  "analsex",
  "andskota",
  "anilingus",
  "anus",
  "apeshit",
  "ar5e",
  "arabush",
  "arabushs",
  "areola",
  "areole",
  "argie",
  "armo",
  "armos",
  "arrse",
  "arschloch",
  "arse",
  "arsehole",
  "aryan",
  "ash0le",
  "ash0les",
  "asholes",
  "ass monkey",
  "ass",
  "ass-fucker",
  "ass-hat",
  "ass-pirate",
  "assbag",
  "assbagger",
  "assbandit",
  "assbang",
  "assbanged",
  "assbanger",
  "assbangs",
  "assbite",
  "assblaster",
  "assclown",
  "asscock",
  "asscowboy",
  "asscracker",
  "asses",
  "assface",
  "assfuck",
  "assfucker",
  "assfukka",
  "assgoblin",
  "assh0le",
  "assh0lez",
  "asshat",
  "asshead",
  "assho1e",
  "asshole",
  "assholes",
  "assholz",
  "asshopper",
  "asshore",
  "assjacker",
  "assjockey",
  "asskiss",
  "asskisser",
  "assklown",
  "asslick",
  "asslicker",
  "asslover",
  "assman",
  "assmaster",
  "assmonkey",
  "assmunch",
  "assmuncher",
  "assnigger",
  "asspacker",
  "asspirate",
  "asspuppies",
  "assrammer",
  "assranger",
  "assshit",
  "assshole",
  "asssucker",
  "asswad",
  "asswhole",
  "asswhore",
  "asswipe",
  "asswipes",
  "auto erotic",
  "autoerotic",
  "ayir",
  "azazel",
  "azz",
  "azzhole",
  "b a s t a r d",
  "b i t c h",
  "b o o b",
  "b!+ch",
  "b!tch",
  "b!tchin",
  "b*tch",
  "b00b",
  "b00bies",
  "b00biez",
  "b00bs",
  "b00bz",
  "b17ch",
  "b1tch",
  "b7ch",
  "babeland",
  "babes",
  "baby batter",
  "baby juice",
  "backdoorman",
  "badfuck",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "ballbag",
  "balllicker",
  "ballsack",
  "bampot",
  "bangbro",
  "bangbros",
  "bangbus",
  "bareback",
  "barely legal",
  "barelylegal",
  "barenaked",
  "barface",
  "barfface",
  "bassterd",
  "bassterds",
  "bastard",
  "bastardo",
  "bastards",
  "bastardz",
  "basterds",
  "basterdz",
  "bastinado",
  "bazongas",
  "bazooms",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beaney",
  "beaneys",
  "beardedclam",
  "beastality",
  "beastial",
  "beastiality",
  "beastility",
  "beatch",
  "beatoff",
  "beatyourmeat",
  "beaver cleaver",
  "beaver lips",
  "beef curtains",
  "beeyotch",
  "bellend",
  "beotch",
  "bestial",
  "bestiality",
  "bi curious",
  "bi+ch",
  "bi7ch",
  "biatch",
  "bicurious",
  "big black",
  "big breasts",
  "big knockers",
  "big tits",
  "bigass",
  "bigbastard",
  "bigbreasts",
  "bigbutt",
  "bigtits",
  "bimbo",
  "bimbos",
  "bint",
  "birdlock",
  "bitch",
  "bitchass",
  "bitched",
  "bitcher",
  "bitchers",
  "bitches",
  "bitchez",
  "bitchin",
  "bitching",
  "bitchslap",
  "bitchtit",
  "bitchy",
  "biteme",
  "bitties",
  "black cock",
  "blackcock",
  "blackman",
  "blacks",
  "blonde action",
  "blonde on blonde action",
  "blonde on blonde",
  "bloodclaat",
  "blow j",
  "blow job",
  "blow your l",
  "blow your load",
  "blowjob",
  "blowjobs",
  "blue waffle",
  "bluegum",
  "bluegums",
  "blumpkin",
  "bo ob",
  "bo obs",
  "boang",
  "boche",
  "boches",
  "boffing",
  "bogan",
  "bohunk",
  "boink",
  "boiolas",
  "bollick",
  "bollock",
  "bollocks",
  "bollok",
  "bollox",
  "bombers",
  "bomd",
  "bondage",
  "boned",
  "boner",
  "boners",
  "bong",
  "boong",
  "boonga",
  "boongas",
  "boongs",
  "boonie",
  "boonies",
  "booobs",
  "boooobs",
  "booooobs",
  "booooooobs",
  "bootee",
  "bootlip",
  "bootlips",
  "boozer",
  "bosch",
  "bosche",
  "bosches",
  "boschs",
  "bosomy",
  "bounty bar",
  "bounty bars",
  "bountybar",
  "brea5t",
  "breastjob",
  "breastlover",
  "breastman",
  "brown shower",
  "brown showers",
  "brunette action",
  "btch",
  "buceta",
  "buddhahead",
  "buddhaheads",
  "buffies",
  "bugger",
  "buggered",
  "buggery",
  "bukake",
  "bukkake",
  "bullcrap",
  "bulldike",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bullshits",
  "bullshitted",
  "bullturds",
  "bumblefuck",
  "bumfuck",
  "bung hole",
  "bung",
  "bunga",
  "bungas",
  "bunghole",
  "bunny fucker",
  "burr head",
  "burr heads",
  "burrhead",
  "burrheads",
  "butchbabes",
  "butchdike",
  "butchdyke",
  "butt plug",
  "butt-pirate",
  "buttbang",
  "buttcheeks",
  "buttface",
  "buttfuck",
  "buttfucker",
  "buttfuckers",
  "butthead",
  "butthole",
  "buttman",
  "buttmuch",
  "buttmunch",
  "buttmuncher",
  "buttpirate",
  "buttplug",
  "buttstain",
  "buttwipe",
  "byatch",
  "c u n t",
  "c-0-c-k",
  "c-o-c-k",
  "c-u-n-t",
  "c.0.c.k",
  "c.o.c.k.",
  "c.u.n.t",
  "c0ck",
  "c0cks",
  "c0cksucker",
  "c0k",
  "cabron",
  "caca",
  "cacker",
  "cahone",
  "camel jockey",
  "camel jockeys",
  "camel toe",
  "cameljockey",
  "cameltoe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "carruth",
  "cawk",
  "cawks",
  "cazzo",
  "chav",
  "cheese eating surrender monkey",
  "cheese eating surrender monkies",
  "cheeseeating surrender monkey",
  "cheeseeating surrender monkies",
  "cheesehead",
  "cheeseheads",
  "cherrypopper",
  "chickslick",
  "china swede",
  "china swedes",
  "chinaman",
  "chinamen",
  "chinaswede",
  "chinaswedes",
  "chinc",
  "chincs",
  "ching chong",
  "ching chongs",
  "chinga",
  "chingchong",
  "chingchongs",
  "chink",
  "chinks",
  "chinky",
  "choad",
  "chocolate rosebuds",
  "chode",
  "chodes",
  "chonkies",
  "chonky",
  "chonkys",
  "chraa",
  "christ killer",
  "christ killers",
  "chug",
  "chugs",
  "chuj",
  "chunger",
  "chungers",
  "chunkies",
  "chunkys",
  "cipa",
  "circlejerk",
  "cl1t",
  "clamdigger",
  "clamdiver",
  "clamps",
  "clansman",
  "clansmen",
  "clanswoman",
  "clanswomen",
  "cleveland steamer",
  "clit",
  "clitface",
  "clitfuck",
  "clitoris",
  "clitorus",
  "clits",
  "clitty",
  "clogwog",
  "clover clamps",
  "clusterfuck",
  "cnts",
  "cntz",
  "cnut",
  "cocain",
  "cocaine",
  "cock",
  "cock-head",
  "cock-sucker",
  "cockbite",
  "cockblock",
  "cockblocker",
  "cockburger",
  "cockcowboy",
  "cockface",
  "cockfight",
  "cockfucker",
  "cockhead",
  "cockholster",
  "cockjockey",
  "cockknob",
  "cockknocker",
  "cockknoker",
  "cocklicker",
  "cocklover",
  "cockmaster",
  "cockmongler",
  "cockmongruel",
  "cockmonkey",
  "cockmunch",
  "cockmuncher",
  "cocknob",
  "cocknose",
  "cocknugget",
  "cockqueen",
  "cockrider",
  "cocks",
  "cockshit",
  "cocksman",
  "cocksmith",
  "cocksmoker",
  "cocksucer",
  "cocksuck",
  "cocksucked",
  "cocksucker",
  "cocksucking",
  "cocksucks",
  "cocksuka",
  "cocksukka",
  "cocktease",
  "cocky",
  "cohee",
  "coital",
  "coitus",
  "cok",
  "cokmuncher",
  "coksucka",
  "condom",
  "coochie",
  "coochy",
  "coolie",
  "coolies",
  "cooly",
  "coon ass",
  "coon asses",
  "coonass",
  "coonasses",
  "coondog",
  "coons",
  "cooter",
  "coprolagnia",
  "coprophilia",
  "copulate",
  "corksucker",
  "cornhole",
  "cra5h",
  "crackcocain",
  "crackpipe",
  "crackwhore",
  "crap",
  "crapola",
  "crapper",
  "crappy",
  "creampie",
  "crotchjockey",
  "crotchmonkey",
  "crotchrot",
  "cuck",
  "cum face",
  "cum licker",
  "cum",
  "cumbubble",
  "cumdumpster",
  "cumfest",
  "cumguzzler",
  "cuming",
  "cumjockey",
  "cumlickr",
  "cumm",
  "cummer",
  "cummin",
  "cumming",
  "cumquat",
  "cumqueen",
  "cums",
  "cumshot",
  "cumshots",
  "cumslut",
  "cumstain",
  "cumsucker",
  "cumtart",
  "cunilingus",
  "cunillingus",
  "cunn",
  "cunnie",
  "cunnilingus",
  "cunntt",
  "cunny",
  "cunt",
  "cunteyed",
  "cuntface",
  "cuntfuck",
  "cuntfucker",
  "cunthole",
  "cunthunter",
  "cuntlick",
  "cuntlicker",
  "cuntlicking",
  "cuntrag",
  "cunts",
  "cuntslut",
  "cuntsucker",
  "cuntz",
  "curry muncher",
  "curry munchers",
  "currymuncher",
  "currymunchers",
  "cushi",
  "cushis",
  "cyalis",
  "cyberfuc",
  "cyberfuck",
  "cyberfucked",
  "cyberfucker",
  "cyberfuckers",
  "cyberfucking",
  "cybersex",
  "cyberslimer",
  "d0ng",
  "d0uch3",
  "d0uche",
  "d1ck",
  "d1ld0",
  "d1ldo",
  "d4mn",
  "dago",
  "dagos",
  "dahmer",
  "damm",
  "dammit",
  "damn",
  "damnit",
  "darkey",
  "darkeys",
  "darkie",
  "darkies",
  "darky",
  "date rape",
  "daterape",
  "datnigga",
  "dawgie style",
  "dawgie-style",
  "daygo",
  "deapthroat",
  "deep throat",
  "deep throating",
  "deepaction",
  "deepthroat",
  "deepthroating",
  "defecate",
  "deggo",
  "dego",
  "degos",
  "dendrophilia",
  "destroyyourpussy",
  "deth",
  "diaper daddy",
  "diaper head",
  "diaper heads",
  "diaperdaddy",
  "diaperhead",
  "diaperheads",
  "dick pic",
  "dick",
  "dick-ish",
  "dickbag",
  "dickbeater",
  "dickbeaters",
  "dickbrain",
  "dickdipper",
  "dickface",
  "dickflipper",
  "dickforbrains",
  "dickfuck",
  "dickhead",
  "dickheads",
  "dickhole",
  "dickish",
  "dickjuice",
  "dickless",
  "dicklick",
  "dicklicker",
  "dickman",
  "dickmilk",
  "dickmonger",
  "dickpic",
  "dickripper",
  "dicks",
  "dicksipper",
  "dickslap",
  "dickslicker",
  "dicksucker",
  "dickwad",
  "dickweasel",
  "dickweed",
  "dickwhipper",
  "dickwod",
  "dickzipper",
  "diddle",
  "dike",
  "dild0",
  "dild0s",
  "dildo",
  "dildos",
  "dilf",
  "diligaf",
  "dilld0",
  "dilld0s",
  "dillweed",
  "dimwit",
  "dingle",
  "dingleberries",
  "dingleberry",
  "dink",
  "dinks",
  "dipship",
  "dipshit",
  "dipstick",
  "dirsa",
  "dirty pillows",
  "dirty sanchez",
  "dix",
  "dixiedike",
  "dixiedyke",
  "dlck",
  "dog style",
  "dog-fucker",
  "doggie style",
  "doggie",
  "doggie-style",
  "doggiestyle",
  "doggin",
  "dogging",
  "doggy style",
  "doggy-style",
  "doggystyle",
  "dolcett",
  "dominatricks",
  "dominatrics",
  "dominatrix",
  "dommes",
  "dong",
  "donkey punch",
  "donkeypunch",
  "donkeyribber",
  "doochbag",
  "doodoo",
  "doofus",
  "dookie",
  "doosh",
  "dot head",
  "dot heads",
  "dothead",
  "dotheads",
  "double dong",
  "double penetration",
  "doubledong",
  "doublepenetration",
  "douch3",
  "douche bag",
  "douche",
  "douche-fag",
  "douchebag",
  "douchebags",
  "douchewaffle",
  "douchey",
  "dp action",
  "dpaction",
  "dragqueen",
  "dragqween",
  "dripdick",
  "dry hump",
  "dryhump",
  "duche",
  "dudette",
  "dumass",
  "dumb ass",
  "dumbass",
  "dumbasses",
  "dumbbitch",
  "dumbfuck",
  "dumbshit",
  "dumshit",
  "dune coon",
  "dune coons",
  "dupa",
  "dvda",
  "dyefly",
  "dyke",
  "dykes",
  "dziwka",
  "earotics",
  "easyslut",
  "eat my ass",
  "eat my",
  "eatadick",
  "eatballs",
  "eathairpie",
  "eatme",
  "eatmyass",
  "eatpussy",
  "ecchi",
  "ejackulate",
  "ejakulate",
  "ekrem",
  "ekto",
  "enculer",
  "enema",
  "erection",
  "ero",
  "erotic",
  "erotism",
  "esqua",
  "essohbee",
  "ethical slut",
  "evl",
  "excrement",
  "exkwew",
  "extacy",
  "extasy",
  "f u c k e r",
  "f u c k e",
  "f u c k",
  "f u k",
  "f*ck",
  "f-u-c-k",
  "f.u.c.k",
  "f4nny",
  "f_u_c_k",
  "facefucker",
  "fack",
  "faeces",
  "faen",
  "fag",
  "fag1t",
  "fagbag",
  "faget",
  "fagfucker",
  "fagg",
  "fagg1t",
  "fagged",
  "fagging",
  "faggit",
  "faggitt",
  "faggot",
  "faggotcock",
  "faggs",
  "fagit",
  "fagot",
  "fagots",
  "fags",
  "fagt",
  "fagtard",
  "fagz",
  "faig",
  "faigs",
  "faigt",
  "fanculo",
  "fannybandit",
  "fannyflaps",
  "fannyfucker",
  "fanyy",
  "fartknocker",
  "fastfuck",
  "fatah",
  "fatfuck",
  "fatfucker",
  "fatso",
  "fck",
  "fckcum",
  "fckd",
  "fcuk",
  "fcuker",
  "fcuking",
  "fecal",
  "feck",
  "fecker",
  "feg",
  "felatio",
  "felch",
  "felcher",
  "felching",
  "fellate",
  "fellatio",
  "feltch",
  "feltcher",
  "feltching",
  "female squirting",
  "femalesquirtin",
  "femalesquirting",
  "femdom",
  "fetish",
  "ficken",
  "figging",
  "fingerbang",
  "fingerfood",
  "fingerfuck",
  "fingerfucked",
  "fingerfucker",
  "fingerfuckers",
  "fingerfucking",
  "fingerfucks",
  "fingering",
  "fisted",
  "fister",
  "fistfuck",
  "fistfucked",
  "fistfucker",
  "fistfuckers",
  "fistfucking",
  "fistfuckings",
  "fistfucks",
  "fisting",
  "fisty",
  "fitt",
  "flamer",
  "flasher",
  "flikker",
  "flipping the bird",
  "flogthelog",
  "floo",
  "floozy",
  "flydie",
  "flydye",
  "foad",
  "fok",
  "fondle",
  "foobar",
  "fook",
  "fooker",
  "foot fetish",
  "footaction",
  "footfetish",
  "footfuck",
  "footfucker",
  "footjob",
  "footlicker",
  "footstar",
  "foreskin",
  "forni",
  "fornicate",
  "fotze",
  "foursome",
  "fourtwenty",
  "freakfuck",
  "freakyfucker",
  "freefuck",
  "freex",
  "frigg",
  "frigga",
  "frigger",
  "frotting",
  "fucck",
  "fuck",
  "fuck-tard",
  "fucka",
  "fuckable",
  "fuckass",
  "fuckbag",
  "fuckbitch",
  "fuckbook",
  "fuckboy",
  "fuckbrain",
  "fuckbuddy",
  "fuckbutt",
  "fuckd",
  "fucked",
  "fuckedup",
  "fucker",
  "fuckers",
  "fuckersucker",
  "fuckface",
  "fuckfest",
  "fuckfreak",
  "fuckfriend",
  "fuckhead",
  "fuckheads",
  "fuckher",
  "fuckhole",
  "fuckin",
  "fuckina",
  "fucking",
  "fuckingbitch",
  "fuckings",
  "fuckingshitmotherfucker",
  "fuckinnuts",
  "fuckinright",
  "fuckit",
  "fuckknob",
  "fuckme",
  "fuckmeat",
  "fuckmehard",
  "fuckmonkey",
  "fuckn",
  "fucknugget",
  "fucknut",
  "fucknuts",
  "fucknutt",
  "fucknutz",
  "fuckoff",
  "fuckpig",
  "fuckpuppet",
  "fuckr",
  "fucks",
  "fuckstick",
  "fucktard",
  "fucktards",
  "fucktoy",
  "fucktrophy",
  "fuckup",
  "fuckwad",
  "fuckwhit",
  "fuckwhore",
  "fuckwit",
  "fuckwitt",
  "fuckyomama",
  "fuckyou",
  "fudge packer",
  "fudgepacker",
  "fugly",
  "fuk",
  "fukah",
  "fuken",
  "fuker",
  "fukin",
  "fuking",
  "fukk",
  "fukkah",
  "fukken",
  "fukker",
  "fukkin",
  "fukking",
  "fuks",
  "fuktard",
  "fuktards",
  "fukwhit",
  "fukwit",
  "funfuck",
  "futanari",
  "futanary",
  "futkretzn",
  "fuuck",
  "fux",
  "fux0r",
  "fuxor",
  "fvck",
  "fvk",
  "fxck",
  "g-spot",
  "g00k",
  "gae",
  "gai",
  "gang bang",
  "gangbang",
  "gangbanged",
  "gangbanger",
  "gangbangs",
  "ganja",
  "gassyass",
  "gator bait",
  "gatorbait",
  "gay sex",
  "gayass",
  "gaybob",
  "gayboy",
  "gaydo",
  "gaygirl",
  "gaylord",
  "gaymuthafuckinwhore",
  "gays",
  "gaysex",
  "gaytard",
  "gaywad",
  "gayz",
  "geezer",
  "geni",
  "genital",
  "genitals",
  "getiton",
  "gey",
  "gfy",
  "ghay",
  "ghey",
  "giant cock",
  "gigolo",
  "ginzo",
  "ginzos",
  "gipp",
  "gippo",
  "gippos",
  "gipps",
  "girl on top",
  "girl on",
  "girls gone wild",
  "givehead",
  "glans",
  "glazeddonut",
  "goatcx",
  "goatse",
  "god dammit",
  "god damn",
  "god damnit",
  "god-dam",
  "god-damned",
  "godam",
  "godammit",
  "godamn",
  "godamnit",
  "goddam",
  "goddamit",
  "goddamm",
  "goddammit",
  "goddamn",
  "goddamned",
  "goddamnes",
  "goddamnit",
  "goddamnmuthafucker",
  "godsdamn",
  "gokkun",
  "golden shower",
  "goldenshower",
  "golliwog",
  "golliwogs",
  "gonad",
  "gonads",
  "gonorrehea",
  "gonzagas",
  "goo girl",
  "gooch",
  "goodpoop",
  "gook eye",
  "gook eyes",
  "gook",
  "gookeye",
  "gookeyes",
  "gookies",
  "gooks",
  "gooky",
  "gora",
  "goras",
  "goregasm",
  "gotohell",
  "goy",
  "goyim",
  "greaseball",
  "greaseballs",
  "groe",
  "groid",
  "groids",
  "grope",
  "grostulation",
  "group sex",
  "gspot",
  "gstring",
  "gtfo",
  "gub",
  "gubba",
  "gubbas",
  "gubs",
  "guido",
  "guiena",
  "guineas",
  "guizi",
  "gummer",
  "guro",
  "gwailo",
  "gwailos",
  "gweilo",
  "gweilos",
  "gyopo",
  "gyopos",
  "gyp",
  "gyped",
  "gypo",
  "gypos",
  "gypp",
  "gypped",
  "gyppie",
  "gyppies",
  "gyppo",
  "gyppos",
  "gyppy",
  "gyppys",
  "gypsys",
  "h e l l",
  "h o m",
  "h00r",
  "h0ar",
  "h0m0",
  "h0mo",
  "h0r",
  "h0re",
  "h4x0r",
  "hadji",
  "hadjis",
  "hairyback",
  "hairybacks",
  "haji",
  "hajis",
  "hajji",
  "hajjis",
  "half breed",
  "half caste",
  "halfbreed",
  "halfcaste",
  "hamas",
  "hamflap",
  "hand job",
  "handjob",
  "haole",
  "haoles",
  "hapa",
  "hard core",
  "hardcore",
  "hardcoresex",
  "hardon",
  "he11",
  "headfuck",
  "hebe",
  "hebes",
  "heeb",
  "heebs",
  "hells",
  "helvete",
  "hentai",
  "heroin",
  "herp",
  "herpes",
  "herpy",
  "heshe",
  "hijacking",
  "hillbillies",
  "hillbilly",
  "hindoo",
  "hiscock",
  "hitler",
  "hitlerism",
  "hitlerist",
  "hoare",
  "hobag",
  "hodgie",
  "hoer",
  "hoes",
  "holestuffer",
  "hom0",
  "homo",
  "homobangers",
  "homodumbshit",
  "homoey",
  "honger",
  "honkers",
  "honkey",
  "honkeys",
  "honkie",
  "honkies",
  "honky",
  "hooch",
  "hooker",
  "hookers",
  "hoor",
  "hoore",
  "hootch",
  "hooter",
  "hooters",
  "hore",
  "hori",
  "horis",
  "hork",
  "horndawg",
  "horndog",
  "horney",
  "horniest",
  "horny",
  "horseshit",
  "hosejob",
  "hoser",
  "hot carl",
  "hot chick",
  "hotcarl",
  "hotdamn",
  "hotpussy",
  "hotsex",
  "hottotrot",
  "how to kill",
  "how to murder",
  "howtokill",
  "howtomurdep",
  "huevon",
  "huge fat",
  "hugefat",
  "hui",
  "hummer",
  "humped",
  "humper",
  "humpher",
  "humphim",
  "humpin",
  "humping",
  "hussy",
  "hustler",
  "hymen",
  "hymie",
  "hymies",
  "iblowu",
  "ike",
  "ikes",
  "ikey",
  "ikeymo",
  "ikeymos",
  "ikwe",
  "illegals",
  "incest",
  "indon",
  "indons",
  "injun",
  "injuns",
  "insest",
  "intercourse",
  "intheass",
  "inthebuff",
  "israels",
  "j3rk0ff",
  "jack off",
  "jack-off",
  "jackass",
  "jackhole",
  "jackoff",
  "jackshit",
  "jacktheripper",
  "jail bait",
  "jailbait",
  "jap",
  "japcrap",
  "japie",
  "japies",
  "japs",
  "jebus",
  "jelly donut",
  "jerk off",
  "jerk-off",
  "jerk0ff",
  "jerked",
  "jerkoff",
  "jerries",
  "jerry",
  "jewboy",
  "jewed",
  "jewess",
  "jiga",
  "jigaboo",
  "jigaboos",
  "jigarooni",
  "jigaroonis",
  "jigg",
  "jigga",
  "jiggabo",
  "jiggaboo",
  "jiggabos",
  "jiggas",
  "jigger",
  "jiggerboo",
  "jiggers",
  "jiggs",
  "jiggy",
  "jigs",
  "jihad",
  "jijjiboo",
  "jijjiboos",
  "jimfish",
  "jisim",
  "jism",
  "jiss",
  "jiz",
  "jizim",
  "jizin",
  "jizjuice",
  "jizm",
  "jizn",
  "jizz",
  "jizzd",
  "jizzed",
  "jizzim",
  "jizzin",
  "jizzn",
  "jizzum",
  "jugg",
  "juggs",
  "jungle bunnies",
  "jungle bunny",
  "junglebunny",
  "junkie",
  "junky",
  "kacap",
  "kacapas",
  "kacaps",
  "kaffer",
  "kaffir",
  "kaffre",
  "kafir",
  "kanake",
  "kanker",
  "katsap",
  "katsaps",
  "kawk",
  "khokhol",
  "khokhols",
  "kigger",
  "kike",
  "kikes",
  "kimchis",
  "kinbaku",
  "kink",
  "kinkster",
  "kinky",
  "kinkyJesus",
  "kissass",
  "kiunt",
  "kkk",
  "klan",
  "klansman",
  "klansmen",
  "klanswoman",
  "klanswomen",
  "klootzak",
  "knobbing",
  "knobead",
  "knobed",
  "knobend",
  "knobhead",
  "knobjocky",
  "knobjokey",
  "knobz",
  "knockers",
  "knulle",
  "kock",
  "kondum",
  "kondums",
  "kooch",
  "kooches",
  "koon",
  "kootch",
  "krap",
  "krappy",
  "kraut",
  "krauts",
  "kuffar",
  "kuk",
  "kuksuger",
  "kum",
  "kumbubble",
  "kumbullbe",
  "kumer",
  "kummer",
  "kumming",
  "kums",
  "kunilingus",
  "kunnilingus",
  "kunt",
  "kunts",
  "kuntz",
  "kurac",
  "kurwa",
  "kushi",
  "kushis",
  "kusi",
  "kwa",
  "kwai lo",
  "kwai los",
  "kwif",
  "kyke",
  "kykes",
  "kyopo",
  "kyopos",
  "kyrpa",
  "l3i+ch",
  "l3i\\+ch",
  "l3itch",
  "labia",
  "lapdance",
  "leather restraint",
  "leather straight",
  "leatherrestraint",
  "lebos",
  "lech",
  "lemon party",
  "lemonparty",
  "leper",
  "lesbain",
  "lesbayn",
  "lesbin",
  "lesbo",
  "lesbos",
  "lez",
  "lezbe",
  "lezbefriends",
  "lezbian",
  "lezbians",
  "lezbo",
  "lezbos",
  "lezz",
  "lezzian",
  "lezzie",
  "lezzies",
  "lezzo",
  "lezzy",
  "libido",
  "licker",
  "licking",
  "lickme",
  "lilniglet",
  "limey",
  "limpdick",
  "limy",
  "lingerie",
  "lipshits",
  "lipshitz",
  "livesex",
  "loadedgun",
  "lolita",
  "lovebone",
  "lovegoo",
  "lovegun",
  "lovejuice",
  "lovemuscle",
  "lovepistol",
  "loverocket",
  "lowlife",
  "lsd",
  "lubejob",
  "lubra",
  "lucifer",
  "luckycammeltoe",
  "lugan",
  "lugans",
  "lusting",
  "lusty",
  "lynch",
  "m-fucking",
  "m0f0",
  "m0fo",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "mabuno",
  "mabunos",
  "macaca",
  "macacas",
  "mafugly",
  "magicwand",
  "mahbuno",
  "mahbunos",
  "make me come",
  "makemecome",
  "makemecum",
  "male squirting",
  "mamhoon",
  "mams",
  "manhater",
  "manpaste",
  "maricon",
  "maricón",
  "marijuana",
  "masochist",
  "masokist",
  "massa",
  "massterbait",
  "masstrbait",
  "masstrbate",
  "mastabate",
  "mastabater",
  "master-bate",
  "masterb8",
  "masterbaiter",
  "masterbat",
  "masterbat3",
  "masterbate",
  "masterbates",
  "masterbating",
  "masterbation",
  "masterbations",
  "masterblaster",
  "mastrabator",
  "masturbat",
  "masturbate",
  "masturbating",
  "masturbation",
  "mattressprincess",
  "mau mau",
  "mau maus",
  "maumau",
  "maumaus",
  "mcfagget",
  "meatbeatter",
  "meatrack",
  "menage",
  "merd",
  "mgger",
  "mggor",
  "mibun",
  "mick",
  "mickeyfinn",
  "mideast",
  "mierda",
  "milf",
  "mindfuck",
  "minge",
  "minger",
  "mo-fo",
  "mockey",
  "mockie",
  "mocky",
  "mof0",
  "mofo",
  "moky",
  "molest",
  "molestation",
  "molester",
  "molestor",
  "moneyshot",
  "mong",
  "monkleigh",
  "moolie",
  "moon cricket",
  "moon crickets",
  "mooncricket",
  "mooncrickets",
  "moron",
  "moskal",
  "moskals",
  "moslem",
  "mosshead",
  "motha fucker",
  "motha fuker",
  "motha fukkah",
  "motha fukker",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "mother fukah",
  "mother fuker",
  "mother fukkah",
  "mother fukker",
  "mother-fucker",
  "motherfuck",
  "motherfucka",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "motherfvcker",
  "motherlovebone",
  "mothrfucker",
  "mouliewop",
  "mound of venus",
  "moundofvenus",
  "mr hands",
  "mrhands",
  "mtherfucker",
  "mthrfuck",
  "mthrfucker",
  "mthrfucking",
  "mtrfck",
  "mtrfuck",
  "mtrfucker",
  "muff diver",
  "muff",
  "muffdive",
  "muffdiver",
  "muffdiving",
  "muffindiver",
  "mufflikcer",
  "muffpuff",
  "muie",
  "mulatto",
  "mulkku",
  "muncher",
  "munging",
  "munt",
  "munter",
  "muschi",
  "mutha fucker",
  "mutha fukah",
  "mutha fuker",
  "mutha fukkah",
  "mutha fukker",
  "muthafecker",
  "muthafuckaz",
  "muthafucker",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "mutherfucking",
  "muthrfucking",
  "mzungu",
  "mzungus",
  "n1gga",
  "n1gger",
  "n1gr",
  "nads",
  "naked",
  "nambla",
  "nastt",
  "nastybitch",
  "nastyho",
  "nastyslut",
  "nastywhore",
  "nawashi",
  "nazi",
  "nazis",
  "nazism",
  "necro",
  "needthedick",
  "negres",
  "negress",
  "negro",
  "negroes",
  "negroid",
  "negros",
  "neonazi",
  "nepesaurio",
  "nig nog",
  "nig",
  "niga",
  "nigar",
  "nigars",
  "nigas",
  "nigers",
  "nigette",
  "nigettes",
  "nigg",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggahs",
  "niggar",
  "niggaracci",
  "niggard",
  "niggarded",
  "niggarding",
  "niggardliness",
  "niggardlinesss",
  "niggardly",
  "niggards",
  "niggars",
  "niggas",
  "niggaz",
  "nigger",
  "niggerhead",
  "niggerhole",
  "niggers",
  "niggle",
  "niggled",
  "niggles",
  "nigglings",
  "niggor",
  "niggress",
  "niggresses",
  "nigguh",
  "nigguhs",
  "niggur",
  "niggurs",
  "niglet",
  "nignog",
  "nigor",
  "nigors",
  "nigr",
  "nigra",
  "nigras",
  "nigre",
  "nigres",
  "nigress",
  "nigs",
  "nigur",
  "niiger",
  "niigr",
  "nimphomania",
  "nimrod",
  "ninny",
  "nipple",
  "nipplering",
  "nipples",
  "nips",
  "nittit",
  "nlgger",
  "nlggor",
  "nob jokey",
  "nob",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "nofuckingway",
  "nog",
  "nookey",
  "nookie",
  "nooky",
  "noonan",
  "nooner",
  "nsfw images",
  "nsfw",
  "nudger",
  "nudie",
  "nudies",
  "numbnuts",
  "nut sack",
  "nutbutter",
  "nutfucker",
  "nutsack",
  "nutten",
  "nympho",
  "nymphomania",
  "o c k",
  "octopussy",
  "omorashi",
  "one cup two girls",
  "one guy one jar",
  "one guy",
  "one jar",
  "ontherag",
  "orafis",
  "orga",
  "orgasim",
  "orgasim;",
  "orgasims",
  "orgasm",
  "orgasmic",
  "orgasms",
  "orgasum",
  "orgies",
  "orgy",
  "oriface",
  "orifiss",
  "orospu",
  "osama",
  "ovum",
  "ovums",
  "p e n i s",
  "p i s",
  "p u s s y",
  "p.u.s.s.y.",
  "p0rn",
  "packi",
  "packie",
  "packy",
  "paddy",
  "paedophile",
  "paki",
  "pakie",
  "pakis",
  "paky",
  "palesimian",
  "pancake face",
  "pancake faces",
  "panooch",
  "pansies",
  "pansy",
  "panti",
  "pantie",
  "panties",
  "panty",
  "paska",
  "payo",
  "pcp",
  "pearlnecklace",
  "pecker",
  "peckerhead",
  "peckerwood",
  "pedo",
  "pedobear",
  "pedophile",
  "pedophilia",
  "pedophiliac",
  "peeenus",
  "peeenusss",
  "peehole",
  "peenus",
  "peepee",
  "peepshow",
  "peepshpw",
  "pegging",
  "peinus",
  "pen1s",
  "penas",
  "pendejo",
  "pendy",
  "penetrate",
  "penetration",
  "peni5",
  "penial",
  "penile",
  "penis",
  "penis-breath",
  "penises",
  "penisfucker",
  "penisland",
  "penislick",
  "penislicker",
  "penispuffer",
  "penthouse",
  "penus",
  "penuus",
  "perse",
  "perv",
  "perversion",
  "peyote",
  "phalli",
  "phallic",
  "phone sex",
  "phonesex",
  "phuc",
  "phuck",
  "phuk",
  "phuked",
  "phuker",
  "phuking",
  "phukked",
  "phukker",
  "phukking",
  "phuks",
  "phungky",
  "phuq",
  "pi55",
  "picaninny",
  "piccaninny",
  "picka",
  "pickaninnies",
  "pickaninny",
  "piece of shit",
  "pieceofshit",
  "piefke",
  "piefkes",
  "pierdol",
  "pigfucker",
  "piker",
  "pikey",
  "piky",
  "pillowbiter",
  "pillu",
  "pimmel",
  "pimp",
  "pimped",
  "pimper",
  "pimpis",
  "pimpjuic",
  "pimpjuice",
  "pimpsimp",
  "pindick",
  "pinko",
  "pis",
  "pises",
  "pisin",
  "pising",
  "pisof",
  "piss pig",
  "piss",
  "piss-off",
  "pissed",
  "pisser",
  "pissers",
  "pisses",
  "pissflap",
  "pissflaps",
  "pisshead",
  "pissin",
  "pissing",
  "pissoff",
  "pisspig",
  "pizda",
  "playboy",
  "playgirl",
  "pleasure chest",
  "pleasurechest",
  "pocha",
  "pochas",
  "pocho",
  "pochos",
  "pocketpool",
  "pohm",
  "pohms",
  "polac",
  "polack",
  "polacks",
  "polak",
  "pole smoker",
  "polesmoker",
  "pollock",
  "pollocks",
  "pommie grant",
  "pommie grants",
  "pommy",
  "ponyplay",
  "poof",
  "poon",
  "poonani",
  "poonany",
  "poontang",
  "poontsee",
  "poop chute",
  "poopchute",
  "pooper",
  "pooperscooper",
  "pooping",
  "poorwhitetrash",
  "popimp",
  "porch monkey",
  "porch monkies",
  "porchmonkey",
  "porn",
  "pornflick",
  "pornking",
  "porno",
  "pornography",
  "pornos",
  "pornprincess",
  "pound town",
  "poundtown",
  "pplicker",
  "pr0n",
  "pr1c",
  "pr1ck",
  "pr1k",
  "prairie nigger",
  "prairie niggers",
  "preteen",
  "pric",
  "prickhead",
  "pricks",
  "prig",
  "prince albert piercing",
  "pron",
  "prostitute",
  "pthc",
  "pu55i",
  "pu55y",
  "pube",
  "pubes",
  "pubic",
  "pubiclice",
  "pubis",
  "pudboy",
  "pudd",
  "puddboy",
  "pula",
  "punani",
  "punanny",
  "punany",
  "punkass",
  "punky",
  "punta",
  "puntang",
  "purinapricness",
  "pusies",
  "puss",
  "pusse",
  "pussee",
  "pussi",
  "pussie",
  "pussies",
  "pussy",
  "pussycat",
  "pussydestroyer",
  "pussyeater",
  "pussyfart",
  "pussyfuck",
  "pussyfucker",
  "pussylicker",
  "pussylicking",
  "pussylips",
  "pussylover",
  "pussypalace",
  "pussypounder",
  "pussys",
  "pusy",
  "puta",
  "puto",
  "puuke",
  "puuker",
  "qahbeh",
  "quashie",
  "queaf",
  "queef",
  "queerhole",
  "queero",
  "queers",
  "queerz",
  "quickie",
  "quicky",
  "quiff",
  "quim",
  "qweers",
  "qweerz",
  "qweir",
  "r-tard",
  "r-tards",
  "r5e",
  "ra8s",
  "raghead",
  "ragheads",
  "rape",
  "raped",
  "raper",
  "raping",
  "rapist",
  "rautenberg",
  "rearend",
  "rearentry",
  "recktum",
  "rectal",
  "rectum",
  "rectus",
  "redleg",
  "redlegs",
  "redlight",
  "redskin",
  "redskins",
  "reefer",
  "reestie",
  "reetard",
  "reich",
  "renob",
  "rentafuck",
  "rere",
  "retard",
  "retarded",
  "retards",
  "retardz",
  "reverse cowgirl",
  "reversecowgirl",
  "rimjaw",
  "rimjob",
  "rimming",
  "ritard",
  "rosebuds",
  "rosy palm and her 5 sisters",
  "rosy palm",
  "rosypalm",
  "rosypalmandher5sisters",
  "rosypalmandherefivesisters",
  "round eyes",
  "roundeye",
  "rtard",
  "rtards",
  "rumprammer",
  "ruski",
  "russki",
  "russkie",
  "rusty trombone",
  "rustytrombone",
  "s h i t",
  "s hit",
  "s&m",
  "s-h-1-t",
  "s-h-i-t",
  "s-o-b",
  "s.h.i.t.",
  "s.o.b.",
  "s0b",
  "s_h_i_t",
  "sadis",
  "sadism",
  "sadist",
  "sadom",
  "sambo",
  "sambos",
  "samckdaddy",
  "sanchez",
  "sand nigger",
  "sand niggers",
  "sandm",
  "sandnigger",
  "santorum",
  "sausagequeen",
  "scag",
  "scallywag",
  "scank",
  "scantily",
  "scat",
  "schaffer",
  "scheiss",
  "schizo",
  "schlampe",
  "schlong",
  "schmuck",
  "schvartse",
  "schvartsen",
  "schwartze",
  "schwartzen",
  "scissoring",
  "screwyou",
  "scroat",
  "scrog",
  "scrote",
  "scrotum",
  "scrud",
  "seduce",
  "semen",
  "seppo",
  "seppos",
  "septics",
  "sex",
  "sexcam",
  "sexed",
  "sexfarm",
  "sexhound",
  "sexhouse",
  "sexi",
  "sexing",
  "sexkitten",
  "sexo",
  "sexpot",
  "sexslave",
  "sextogo",
  "sextoy",
  "sextoys",
  "sexual",
  "sexually",
  "sexwhore",
  "sexx",
  "sexxi",
  "sexxx",
  "sexxxi",
  "sexxxy",
  "sexxy",
  "sexy",
  "sexymoma",
  "sexyslim",
  "sh!+",
  "sh!t",
  "sh1t",
  "sh1ter",
  "sh1ts",
  "sh1tter",
  "sh1tz",
  "shag",
  "shagger",
  "shaggin",
  "shagging",
  "shamedame",
  "sharmuta",
  "sharmute",
  "shat",
  "shav",
  "shaved beaver",
  "shaved pussy",
  "shavedbeaver",
  "shavedpussy",
  "shawtypimp",
  "sheeney",
  "shemale",
  "shhit",
  "shi+",
  "shibari",
  "shibary",
  "shinola",
  "shipal",
  "shit ass",
  "shit",
  "shit-ass",
  "shit-bag",
  "shit-bagger",
  "shit-brain",
  "shit-breath",
  "shit-cunt",
  "shit-dick",
  "shit-eating",
  "shit-face",
  "shit-faced",
  "shit-fit",
  "shit-head",
  "shit-heel",
  "shit-hole",
  "shit-house",
  "shit-load",
  "shit-pot",
  "shit-spitter",
  "shit-stain",
  "shitass",
  "shitbag",
  "shitbagger",
  "shitblimp",
  "shitbrain",
  "shitbreath",
  "shitcan",
  "shitcunt",
  "shitdick",
  "shite",
  "shiteater",
  "shiteating",
  "shited",
  "shitey",
  "shitface",
  "shitfaced",
  "shitfit",
  "shitforbrains",
  "shitfuck",
  "shitfucker",
  "shitfull",
  "shithapens",
  "shithappens",
  "shithead",
  "shitheel",
  "shithole",
  "shithouse",
  "shiting",
  "shitings",
  "shitlist",
  "shitload",
  "shitola",
  "shitoutofluck",
  "shitpot",
  "shits",
  "shitspitter",
  "shitstain",
  "shitt",
  "shitted",
  "shitter",
  "shitters",
  "shittiest",
  "shitting",
  "shittings",
  "shitty",
  "shity",
  "shitz",
  "shiz",
  "shiznit",
  "shortfuck",
  "shota",
  "shylock",
  "shylocks",
  "shyt",
  "shyte",
  "shytty",
  "shyty",
  "simp",
  "sissy",
  "sixsixsix",
  "sixtynine",
  "sixtyniner",
  "skag",
  "skanck",
  "skank",
  "skankbitch",
  "skankee",
  "skankey",
  "skankfuck",
  "skanks",
  "skankwhore",
  "skanky",
  "skankybitch",
  "skankywhore",
  "skeet",
  "skinflute",
  "skribz",
  "skullfuck",
  "skum",
  "skumbag",
  "skurwysyn",
  "skwa",
  "skwe",
  "slag",
  "slanteye",
  "slanty",
  "slapper",
  "sleezeball",
  "slideitin",
  "slimeball",
  "slimebucket",
  "slopehead",
  "slopeheads",
  "sloper",
  "slopers",
  "slopey",
  "slopeys",
  "slopies",
  "slopy",
  "slut",
  "slutbag",
  "slutbucket",
  "slutdumper",
  "slutkiss",
  "sluts",
  "slutt",
  "slutting",
  "slutty",
  "slutwear",
  "slutwhore",
  "slutz",
  "smackthemonkey",
  "smeg",
  "smegma",
  "smut",
  "smutty",
  "snatchpatch",
  "sniggered",
  "sniggering",
  "sniggers",
  "snowback",
  "snowballing",
  "snownigger",
  "snuff",
  "socksucker",
  "sodom",
  "sodomise",
  "sodomite",
  "sodomize",
  "sodomy",
  "son of a bitch",
  "son of a whore",
  "son-of-a-bitch",
  "son-of-a-whore",
  "sonofabitch",
  "sonofbitch",
  "sooties",
  "souse",
  "soused",
  "soyboy",
  "spac",
  "spaghettibender",
  "spaghettinigger",
  "spank",
  "spankthemonkey",
  "spastic",
  "spearchucker",
  "spearchuckers",
  "sperm",
  "spermacide",
  "spermbag",
  "spermhearder",
  "spermherder",
  "sphencter",
  "spic",
  "spick",
  "spicks",
  "spics",
  "spierdalaj",
  "spig",
  "spigotty",
  "spik",
  "spiks",
  "splittail",
  "splooge",
  "spludge",
  "spooge",
  "spread legs",
  "spreadeagle",
  "spunk",
  "spunky",
  "sqeh",
  "squa",
  "squarehead",
  "squareheads",
  "squaw",
  "squinty",
  "squirting",
  "stagg",
  "stfu",
  "stiffy",
  "stoned",
  "stoner",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "stripclub",
  "stroking",
  "stuinties",
  "stupidfuck",
  "stupidfucker",
  "style doggy",
  "suckdick",
  "sucked",
  "sucker",
  "sucking",
  "suckme",
  "suckmyass",
  "suckmydick",
  "suckmytit",
  "suckoff",
  "suicide girl",
  "suicide girls",
  "suicidegirl",
  "suicidegirls",
  "suka",
  "sultrywoman",
  "sultrywomen",
  "sumofabiatch",
  "swallower",
  "swalow",
  "swamp guinea",
  "swamp guineas",
  "swastika",
  "syphilis",
  "t i t",
  "t i ts",
  "t1t",
  "t1tt1e5",
  "t1tties",
  "tacohead",
  "tacoheads",
  "taff",
  "take off your",
  "tar babies",
  "tar baby",
  "tarbaby",
  "tard",
  "taste my",
  "tastemy",
  "tawdry",
  "tea bagging",
  "teabagging",
  "teat",
  "teets",
  "teez",
  "terd",
  "teste",
  "testee",
  "testes",
  "testical",
  "testicle",
  "testicles",
  "testis",
  "thicklip",
  "thicklips",
  "thirdeye",
  "thirdleg",
  "threesome",
  "threeway",
  "throating",
  "thumbzilla",
  "thundercunt",
  "tied up",
  "tig ol bitties",
  "tig old bitties",
  "tight white",
  "timber nigger",
  "timber niggers",
  "timbernigger",
  "tit",
  "titbitnipply",
  "titfuck",
  "titfucker",
  "titfuckin",
  "titi",
  "titjob",
  "titlicker",
  "titlover",
  "tits",
  "titt",
  "tittie",
  "tittie5",
  "tittiefucker",
  "titties",
  "tittis",
  "titty",
  "tittyfuck",
  "tittyfucker",
  "tittys",
  "tittywank",
  "titwank",
  "tity",
  "to murder",
  "tongethruster",
  "tongue in a",
  "tongueina",
  "tonguethrust",
  "tonguetramp",
  "toots",
  "topless",
  "tortur",
  "torture",
  "tosser",
  "towel head",
  "towel heads",
  "towelhead",
  "trailertrash",
  "trannie",
  "tranny",
  "transsexual",
  "transvestite",
  "tribadism",
  "trisexual",
  "trois",
  "trots",
  "tub girl",
  "tubgirl",
  "tuckahoe",
  "tunneloflove",
  "turd burgler",
  "turnon",
  "tush",
  "tushy",
  "tw4t",
  "twat",
  "twathead",
  "twatlips",
  "twats",
  "twatty",
  "twatwaffle",
  "twink",
  "twinkie",
  "two girls one cup",
  "twobitwhore",
  "twunt",
  "twunter",
  "udge packer",
  "ukrop",
  "unclefucker",
  "unfuckable",
  "upskirt",
  "uptheass",
  "upthebutt",
  "urethra play",
  "urethraplay",
  "urophilia",
  "usama",
  "ussys",
  "uzi",
  "v a g i n a",
  "v14gra",
  "v1gra",
  "v4gra",
  "va-j-j",
  "va1jina",
  "vag",
  "vag1na",
  "vagiina",
  "vaj1na",
  "vajina",
  "valium",
  "venus mound",
  "vgra",
  "vibr",
  "vibrater",
  "vibrator",
  "vigra",
  "violet wand",
  "virginbreaker",
  "vittu",
  "vixen",
  "vjayjay",
  "vorarephilia",
  "voyeurweb",
  "voyuer",
  "vullva",
  "vulva",
  "w00se",
  "w0p",
  "wab",
  "wang",
  "wank",
  "wanker",
  "wanking",
  "wanky",
  "waysted",
  "wazoo",
  "weenie",
  "weewee",
  "weiner",
  "welcher",
  "wench",
  "wet dream",
  "wetb",
  "wetback",
  "wetbacks",
  "wetdream",
  "wetspot",
  "wh00r",
  "wh0re",
  "wh0reface",
  "whacker",
  "whash",
  "whigger",
  "whiggers",
  "whiskeydick",
  "whiskydick",
  "whit",
  "white power",
  "white trash",
  "whitenigger",
  "whitepower",
  "whitetrash",
  "whitey",
  "whiteys",
  "whities",
  "whoar",
  "whop",
  "whoralicious",
  "whore",
  "whorealicious",
  "whorebag",
  "whored",
  "whoreface",
  "whorefucker",
  "whorehopper",
  "whorehouse",
  "whores",
  "whoring",
  "wichser",
  "wigga",
  "wiggas",
  "wigger",
  "wiggers",
  "willie",
  "willies",
  "williewanker",
  "willy",
  "wog",
  "wogs",
  "woose",
  "wop",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "wtf",
  "wuss",
  "wuzzie",
  "x-rated",
  "x-rated2g1c",
  "xkwe",
  "xrated",
  "xtc",
  "xx",
  "xxx",
  "xxxxxx",
  "yank",
  "yaoi",
  "yarpie",
  "yarpies",
  "yed",
  "yellow showers",
  "yellowman",
  "yellowshowers",
  "yid",
  "yids",
  "yiffy",
  "yobbo",
  "yourboobs",
  "yourpenis",
  "yourtits",
  "yury",
  "zabourah",
  "zigabo",
  "zigabos",
  "zipperhead",
  "zipperheads",
  "zoophile",
  "zoophilia", 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted', 'aborts', 'abrade', 'abrasive', 'abrupt', 'abruptly', 'abscond', 'absence', 'absent-minded', 'absentee', 'absurd', 'absurdity', 'absurdly', 'absurdness', 'abuse', 'abused', 'abuses', 'abusive', 'abysmal', 'abysmally', 'abyss', 'accidental', 'accost', 'accursed', 'accusation', 'accusations', 'accuse', 'accuses', 'accusing', 'accusingly', 'acerbate', 'acerbic', 'acerbically', 'ache', 'ached', 'aches', 'achey', 'aching', 'acrid', 'acridly', 'acridness', 'acrimonious', 'acrimoniously', 'acrimony', 'adamant', 'adamantly', 'addict', 'addicted', 'addicting', 'addicts', 'admonish', 'admonisher', 'admonishingly', 'admonishment', 'admonition', 'adulterate', 'adulterated', 'adulteration', 'adulterier', 'adversarial', 'adversary', 'adverse', 'adversity', 'afflict', 'affliction', 'afflictive', 'affront', 'afraid', 'aggravate', 'aggravating', 'aggravation', 'aggression', 'aggressive', 'aggressiveness', 'aggressor', 'aggrieve', 'aggrieved', 'aggrivation', 'aghast', 'agonies', 'agonize', 'agonizing', 'agonizingly', 'agony', 'aground', 'ail', 'ailing', 'ailment', 'aimless', 'alarm', 'alarmed', 'alarming', 'alarmingly', 'alienate', 'alienated', 'alienation', 'allegation', 'allegations', 'allege', 'allergic', 'allergies', 'allergy', 'aloof', 'altercation', 'ambiguity', 'ambiguous', 'ambivalence', 'ambivalent', 'ambush', 'amiss', 'amputate', 'anarchism', 'anarchist', 'anarchistic', 'anarchy', 'anemic', 'anger', 'angrily', 'angriness', 'angry', 'anguish', 'animosity', 'annihilate', 'annihilation', 'annoy', 'annoyance', 'annoyances', 'annoyed', 'annoying', 'annoyingly', 'annoys', 'anomalous', 'anomaly', 'antagonism', 'antagonist', 'antagonistic', 'antagonize', 'anti-', 'anti-american', 'anti-israeli', 'anti-occupation', 'anti-proliferation', 'anti-semites', 'anti-social', 'anti-us', 'anti-white', 'antipathy', 'antiquated', 'antithetical', 'anxieties', 'anxiety', 'anxious', 'anxiously', 'anxiousness', 'apathetic', 'apathetically', 'apathy', 'apocalypse', 'apocalyptic', 'apologist', 'apologists', 'appal', 'appall', 'appalled', 'appalling', 'appallingly', 'apprehension', 'apprehensions', 'apprehensive', 'apprehensively', 'arbitrary', 'arcane', 'archaic', 'arduous', 'arduously', 'argumentative', 'arrogance', 'arrogant', 'arrogantly', 'ashamed', 'asinine', 'asininely', 'asinininity', 'askance', 'asperse', 'aspersion', 'aspersions', 'assail', 'assassin', 'assassinate', 'assault', 'assult', 'astray', 'asunder', 'atrocious', 'atrocities', 'atrocity', 'atrophy', 'attack', 'attacks', 'audacious', 'audaciously', 'audaciousness', 'audacity', 'audiciously', 'austere', 'authoritarian', 'autocrat', 'autocratic', 'avalanche', 'avarice', 'avaricious', 'avariciously', 'avenge', 'averse', 'aversion', 'aweful', 'awful', 'awfully', 'awfulness', 'awkward', 'awkwardness', 'ax', 'babble', 'back-logged', 'back-wood', 'back-woods', 'backache', 'backaches', 'backaching', 'backbite', 'backbiting', 'backward', 'backwardness', 'backwood', 'backwoods', 'bad', 'badly', 'baffle', 'baffled', 'bafflement', 'baffling', 'bait', 'balk', 'banal', 'banalize', 'bane', 'banish', 'banishment', 'bankrupt', 'barbarian', 'barbaric', 'barbarically', 'barbarity', 'barbarous', 'barbarously', 'barren', 'baseless', 'bash', 'bashed', 'bashful', 'bashing', 'bastard', 'bastards', 'battered', 'battering', 'batty', 'bearish', 'beastly', 'bedlam', 'bedlamite', 'befoul', 'beg', 'beggar', 'beggarly', 'begging', 'beguile', 'belabor', 'belated', 'beleaguer', 'belie', 'belittle', 'belittled', 'belittling', 'bellicose', 'belligerence', 'belligerent', 'belligerently', 'bemoan', 'bemoaning', 'bemused', 'bent', 'berate', 'bereave', 'bereavement', 'bereft', 'berserk', 'beseech', 'beset', 'besiege', 'besmirch', 'bestial', 'betray', 'betrayal', 'betrayals', 'betrayer', 'betraying', 'betrays', 'bewail', 'beware', 'bewilder', 'bewildered', 'bewildering', 'bewilderingly', 'bewilderment', 'bewitch', 'bias', 'biased', 'biases', 'bicker', 'bickering', 'bid-rigging', 'bigotries', 'bigotry', 'bitch', 'bitchy', 'biting', 'bitingly', 'bitter', 'bitterly', 'bitterness', 'bizarre', 'blab', 'blabber', 'blackmail', 'blah', 'blame', 'blameworthy', 'bland', 'blandish', 'blaspheme', 'blasphemous', 'blasphemy', 'blasted', 'blatant', 'blatantly', 'blather', 'bleak', 'bleakly', 'bleakness', 'bleed', 'bleeding', 'bleeds', 'blemish', 'blind', 'blinding', 'blindingly', 'blindside', 'blister', 'blistering', 'bloated', 'blockage', 'blockhead', 'bloodshed', 'bloodthirsty', 'bloody', 'blotchy', 'blow', 'blunder', 'blundering', 'blunders', 'blunt', 'blur', 'bluring', 'blurred', 'blurring', 'blurry', 'blurs', 'blurt', 'boastful', 'boggle', 'bogus', 'boil', 'boiling', 'boisterous', 'bomb', 'bombard', 'bombardment', 'bombastic', 'bondage', 'bonkers', 'bore', 'bored', 'boredom', 'bores', 'boring', 'botch', 'bother', 'bothered', 'bothering', 'bothers', 'bothersome', 'bowdlerize', 'boycott', 'braggart', 'bragger', 'brainless', 'brainwash', 'brash', 'brashly', 'brashness', 'brat', 'bravado', 'brazen', 'brazenly', 'brazenness', 'breach', 'break', 'break-up', 'break-ups', 'breakdown', 'breaking', 'breaks', 'breakup', 'breakups', 'bribery', 'brimstone', 'bristle', 'brittle', 'broke', 'broken', 'broken-hearted', 'brood', 'browbeat', 'bruise', 'bruised', 'bruises', 'bruising', 'brusque', 'brutal', 'brutalising', 'brutalities', 'brutality', 'brutalize', 'brutalizing', 'brutally', 'brute', 'brutish', 'bs', 'buckle', 'bug', 'bugging', 'buggy', 'bugs', 'bulkier', 'bulkiness', 'bulky', 'bulkyness', 'bull****', 'bull----', 'bullies', 'bullshit', 'bullshyt', 'bully', 'bullying', 'bullyingly', 'bum', 'bump', 'bumped', 'bumping', 'bumpping', 'bumps', 'bumpy', 'bungle', 'bungler', 'bungling', 'bunk', 'burden', 'burdensome', 'burdensomely', 'burn', 'burned', 'burning', 'burns', 'bust', 'busts', 'busybody', 'butcher', 'butchery', 'buzzing', 'byzantine', 'cackle', 'calamities', 'calamitous', 'calamitously', 'calamity', 'callous', 'calumniate', 'calumniation', 'calumnies', 'calumnious', 'calumniously', 'calumny', 'cancer', 'cancerous', 'cannibal', 'cannibalize', 'capitulate', 'capricious', 'capriciously', 'capriciousness', 'capsize', 'careless', 'carelessness', 'caricature', 'carnage', 'carp', 'cartoonish', 'cash-strapped', 'castigate', 'castrated', 'casualty', 'cataclysm', 'cataclysmal', 'cataclysmic', 'cataclysmically', 'catastrophe', 'catastrophes', 'catastrophic', 'catastrophically', 'catastrophies', 'caustic', 'caustically', 'cautionary', 'cave', 'censure', 'chafe', 'chaff', 'chagrin', 'challenging', 'chaos', 'chaotic', 'chasten', 'chastise', 'chastisement', 'chatter', 'chatterbox', 'cheap', 'cheapen', 'cheaply', 'cheat', 'cheated', 'cheater', 'cheating', 'cheats', 'checkered', 'cheerless', 'cheesy', 'chide', 'childish', 'chill', 'chilly', 'chintzy', 'choke', 'choleric', 'choppy', 'chore', 'chronic', 'chunky', 'clamor', 'clamorous', 'clash', 'cliche', 'cliched', 'clique', 'clog', 'clogged', 'clogs', 'cloud', 'clouding', 'cloudy', 'clueless', 'clumsy', 'clunky', 'coarse', 'cocky', 'coerce', 'coercion', 'coercive', 'cold', 'coldly', 'collapse', 'collude', 'collusion', 'combative', 'combust', 'comical', 'commiserate', 'commonplace', 'commotion', 'commotions', 'complacent', 'complain', 'complained', 'complaining', 'complains', 'complaint', 'complaints', 'complex', 'complicated', 'complication', 'complicit', 'compulsion', 'compulsive', 'concede', 'conceded', 'conceit', 'conceited', 'concen', 'concens', 'concern', 'concerned', 'concerns', 'concession', 'concessions', 'condemn', 'condemnable', 'condemnation', 'condemned', 'condemns', 'condescend', 'condescending', 'condescendingly', 'condescension', 'confess', 'confession', 'confessions', 'confined', 'conflict', 'conflicted', 'conflicting', 'conflicts', 'confound', 'confounded', 'confounding', 'confront', 'confrontation', 'confrontational', 'confuse', 'confused', 'confuses', 'confusing', 'confusion', 'confusions', 'congested', 'congestion', 'cons', 'conscons', 'conservative', 'conspicuous', 'conspicuously', 'conspiracies', 'conspiracy', 'conspirator', 'conspiratorial', 'conspire', 'consternation', 'contagious', 'contaminate', 'contaminated', 'contaminates', 'contaminating', 'contamination', 'contempt', 'contemptible', 'contemptuous', 'contemptuously', 'contend', 'contention', 'contentious', 'contort', 'contortions', 'contradict', 'contradiction', 'contradictory', 'contrariness', 'contravene', 'contrive', 'contrived', 'controversial', 'controversy', 'convoluted', 'corrode', 'corrosion', 'corrosions', 'corrosive', 'corrupt', 'corrupted', 'corrupting', 'corruption', 'corrupts', 'corruptted', 'costlier', 'costly', 'counter-productive', 'counterproductive', 'coupists', 'covetous', 'coward', 'cowardly', 'crabby', 'crack', 'cracked', 'cracks', 'craftily', 'craftly', 'crafty', 'cramp', 'cramped', 'cramping', 'cranky', 'crap', 'crappy', 'craps', 'crash', 'crashed', 'crashes', 'crashing', 'crass', 'craven', 'cravenly', 'craze', 'crazily', 'craziness', 'crazy', 'creak', 'creaking', 'creaks', 'credulous', 'creep', 'creeping', 'creeps', 'creepy', 'crept', 'crime', 'criminal', 'cringe', 'cringed', 'cringes', 'cripple', 'crippled', 'cripples', 'crippling', 'crisis', 'critic', 'critical', 'criticism', 'criticisms', 'criticize', 'criticized', 'criticizing', 'critics', 'cronyism', 'crook', 'crooked', 'crooks', 'crowded', 'crowdedness', 'crude', 'cruel', 'crueler', 'cruelest', 'cruelly', 'cruelness', 'cruelties', 'cruelty', 'crumble', 'crumbling', 'crummy', 'crumple', 'crumpled', 'crumples', 'crush', 'crushed', 'crushing', 'cry', 'culpable', 'culprit', 'cumbersome', 'cunt', 'cunts', 'cuplrit', 'curse', 'cursed', 'curses', 'curt', 'cuss', 'cussed', 'cutthroat', 'cynical', 'cynicism', 'd*mn', 'damage', 'damaged', 'damages', 'damaging', 'damn', 'damnable', 'damnably', 'damnation', 'damned', 'damning', 'damper', 'danger', 'dangerous', 'dangerousness', 'dark', 'darken', 'darkened', 'darker', 'darkness', 'dastard', 'dastardly', 'daunt', 'daunting', 'dauntingly', 'dawdle', 'daze', 'dazed', 'dead', 'deadbeat', 'deadlock', 'deadly', 'deadweight', 'deaf', 'dearth', 'death', 'debacle', 'debase', 'debasement', 'debaser', 'debatable', 'debauch', 'debaucher', 'debauchery', 'debilitate', 'debilitating', 'debility', 'debt', 'debts', 'decadence', 'decadent', 'decay', 'decayed', 'deceit', 'deceitful', 'deceitfully', 'deceitfulness', 'deceive', 'deceiver', 'deceivers', 'deceiving', 'deception', 'deceptive', 'deceptively', 'declaim', 'decline', 'declines', 'declining', 'decrement', 'decrepit', 'decrepitude', 'decry', 'defamation', 'defamations', 'defamatory', 'defame', 'defect', 'defective', 'defects', 'defensive', 'defiance', 'defiant', 'defiantly', 'deficiencies', 'deficiency', 'deficient', 'defile', 'defiler', 'deform', 'deformed', 'defrauding', 'defunct', 'defy', 'degenerate', 'degenerately', 'degeneration', 'degradation', 'degrade', 'degrading', 'degradingly', 'dehumanization', 'dehumanize', 'deign', 'deject', 'dejected', 'dejectedly', 'dejection', 'delay', 'delayed', 'delaying', 'delays', 'delinquency', 'delinquent', 'delirious', 'delirium', 'delude', 'deluded', 'deluge', 'delusion', 'delusional', 'delusions', 'demean', 'demeaning', 'demise', 'demolish', 'demolisher', 'demon', 'demonic', 'demonize', 'demonized', 'demonizes', 'demonizing', 'demoralize', 'demoralizing', 'demoralizingly', 'denial', 'denied', 'denies', 'denigrate', 'denounce', 'dense', 'dent', 'dented', 'dents', 'denunciate', 'denunciation', 'denunciations', 'deny', 'denying', 'deplete', 'deplorable', 'deplorably', 'deplore', 'deploring', 'deploringly', 'deprave', 'depraved', 'depravedly', 'deprecate', 'depress', 'depressed', 'depressing', 'depressingly', 'depression', 'depressions', 'deprive', 'deprived', 'deride', 'derision', 'derisive', 'derisively', 'derisiveness', 'derogatory', 'desecrate', 'desert', 'desertion', 'desiccate', 'desiccated', 'desititute', 'desolate', 'desolately', 'desolation', 'despair', 'despairing', 'despairingly', 'desperate', 'desperately', 'desperation', 'despicable', 'despicably', 'despise', 'despised', 'despoil', 'despoiler', 'despondence', 'despondency', 'despondent', 'despondently', 'despot', 'despotic', 'despotism', 'destabilisation', 'destains', 'destitute', 'destitution', 'destroy', 'destroyer', 'destruction', 'destructive', 'desultory', 'deter', 'deteriorate', 'deteriorating', 'deterioration', 'deterrent', 'detest', 'detestable', 'detestably', 'detested', 'detesting', 'detests', 'detract', 'detracted', 'detracting', 'detraction', 'detracts', 'detriment', 'detrimental', 'devastate', 'devastated', 'devastates', 'devastating', 'devastatingly', 'devastation', 'deviate', 'deviation', 'devil', 'devilish', 'devilishly', 'devilment', 'devilry', 'devious', 'deviously', 'deviousness', 'devoid', 'diabolic', 'diabolical', 'diabolically', 'diametrically', 'diappointed', 'diatribe', 'diatribes', 'dick', 'dictator', 'dictatorial', 'die', 'die-hard', 'died', 'dies', 'difficult', 'difficulties', 'difficulty', 'diffidence', 'dilapidated', 'dilemma', 'dilly-dally', 'dim', 'dimmer', 'din', 'ding', 'dings', 'dinky', 'dire', 'direly', 'direness', 'dirt', 'dirtbag', 'dirtbags', 'dirts', 'dirty', 'disable', 'disabled', 'disaccord', 'disadvantage', 'disadvantaged', 'disadvantageous', 'disadvantages', 'disaffect', 'disaffected', 'disaffirm', 'disagree', 'disagreeable', 'disagreeably', 'disagreed', 'disagreeing', 'disagreement', 'disagrees', 'disallow', 'disapointed', 'disapointing', 'disapointment', 'disappoint', 'disappointed', 'disappointing', 'disappointingly', 'disappointment', 'disappointments', 'disappoints', 'disapprobation', 'disapproval', 'disapprove', 'disapproving', 'disarm', 'disarray', 'disaster', 'disasterous', 'disastrous', 'disastrously', 'disavow', 'disavowal', 'disbelief', 'disbelieve', 'disbeliever', 'disclaim', 'discombobulate', 'discomfit', 'discomfititure', 'discomfort', 'discompose', 'disconcert', 'disconcerted', 'disconcerting', 'disconcertingly', 'disconsolate', 'disconsolately', 'disconsolation', 'discontent', 'discontented', 'discontentedly', 'discontinued', 'discontinuity', 'discontinuous', 'discord', 'discordance', 'discordant', 'discountenance', 'discourage', 'discouragement', 'discouraging', 'discouragingly', 'discourteous', 'discourteously', 'discoutinous', 'discredit', 'discrepant', 'discriminate', 'discrimination', 'discriminatory', 'disdain', 'disdained', 'disdainful', 'disdainfully', 'disfavor', 'disgrace', 'disgraced', 'disgraceful', 'disgracefully', 'disgruntle', 'disgruntled', 'disgust', 'disgusted', 'disgustedly', 'disgustful', 'disgustfully', 'disgusting', 'disgustingly', 'dishearten', 'disheartening', 'dishearteningly', 'dishonest', 'dishonestly', 'dishonesty', 'dishonor', 'dishonorable', 'dishonorablely', 'disillusion', 'disillusioned', 'disillusionment', 'disillusions', 'disinclination', 'disinclined', 'disingenuous', 'disingenuously', 'disintegrate', 'disintegrated', 'disintegrates', 'disintegration', 'disinterest', 'disinterested', 'dislike', 'disliked', 'dislikes', 'disliking', 'dislocated', 'disloyal', 'disloyalty', 'dismal', 'dismally', 'dismalness', 'dismay', 'dismayed', 'dismaying', 'dismayingly', 'dismissive', 'dismissively', 'disobedience', 'disobedient', 'disobey', 'disoobedient', 'disorder', 'disordered', 'disorderly', 'disorganized', 'disorient', 'disoriented', 'disown', 'disparage', 'disparaging', 'disparagingly', 'dispensable', 'dispirit', 'dispirited', 'dispiritedly', 'dispiriting', 'displace', 'displaced', 'displease', 'displeased', 'displeasing', 'displeasure', 'disproportionate', 'disprove', 'disputable', 'dispute', 'disputed', 'disquiet', 'disquieting', 'disquietingly', 'disquietude', 'disregard', 'disregardful', 'disreputable', 'disrepute', 'disrespect', 'disrespectable', 'disrespectablity', 'disrespectful', 'disrespectfully', 'disrespectfulness', 'disrespecting', 'disrupt', 'disruption', 'disruptive', 'diss', 'dissapointed', 'dissappointed', 'dissappointing', 'dissatisfaction', 'dissatisfactory', 'dissatisfied', 'dissatisfies', 'dissatisfy', 'dissatisfying', 'dissed', 'dissemble', 'dissembler', 'dissension', 'dissent', 'dissenter', 'dissention', 'disservice', 'disses', 'dissidence', 'dissident', 'dissidents', 'dissing', 'dissocial', 'dissolute', 'dissolution', 'dissonance', 'dissonant', 'dissonantly', 'dissuade', 'dissuasive', 'distains', 'distaste', 'distasteful', 'distastefully', 'distort', 'distorted', 'distortion', 'distorts', 'distract', 'distracting', 'distraction', 'distraught', 'distraughtly', 'distraughtness', 'distress', 'distressed', 'distressing', 'distressingly', 'distrust', 'distrustful', 'distrusting', 'disturb', 'disturbance', 'disturbed', 'disturbing', 'disturbingly', 'disunity', 'disvalue', 'divergent', 'divisive', 'divisively', 'divisiveness', 'dizzing', 'dizzingly', 'dizzy', 'doddering', 'dodgey', 'dogged', 'doggedly', 'dogmatic', 'doldrums', 'domineer', 'domineering', 'donside', 'doom', 'doomed', 'doomsday', 'dope', 'doubt', 'doubtful', 'doubtfully', 'doubts', 'douchbag', 'douchebag', 'douchebags', 'downbeat', 'downcast', 'downer', 'downfall', 'downfallen', 'downgrade', 'downhearted', 'downheartedly', 'downhill', 'downside', 'downsides', 'downturn', 'downturns', 'drab', 'draconian', 'draconic', 'drag', 'dragged', 'dragging', 'dragoon', 'drags', 'drain', 'drained', 'draining', 'drains', 'drastic', 'drastically', 'drawback', 'drawbacks', 'dread', 'dreadful', 'dreadfully', 'dreadfulness', 'dreary', 'dripped', 'dripping', 'drippy', 'drips', 'drones', 'droop', 'droops', 'drop-out', 'drop-outs', 'dropout', 'dropouts', 'drought', 'drowning', 'drunk', 'drunkard', 'drunken', 'dubious', 'dubiously', 'dubitable', 'dud', 'dull', 'dullard', 'dumb', 'dumbfound', 'dump', 'dumped', 'dumping', 'dumps', 'dunce', 'dungeon', 'dungeons', 'dupe', 'dust', 'dusty', 'dwindling', 'dying', 'earsplitting', 'eccentric', 'eccentricity', 'effigy', 'effrontery', 'egocentric', 'egomania', 'egotism', 'egotistical', 'egotistically', 'egregious', 'egregiously', 'election-rigger', 'elimination', 'emaciated', 'emasculate', 'embarrass', 'embarrassing', 'embarrassingly', 'embarrassment', 'embattled', 'embroil', 'embroiled', 'embroilment', 'emergency', 'emphatic', 'emphatically', 'emptiness', 'encroach', 'encroachment', 'endanger', 'enemies', 'enemy', 'enervate', 'enfeeble', 'enflame', 'engulf', 'enjoin', 'enmity', 'enrage', 'enraged', 'enraging', 'enslave', 'entangle', 'entanglement', 'entrap', 'entrapment', 'envious', 'enviously', 'enviousness', 'epidemic', 'equivocal', 'erase', 'erode', 'erodes', 'erosion', 'err', 'errant', 'erratic', 'erratically', 'erroneous', 'erroneously', 'error', 'errors', 'eruptions', 'escapade', 'eschew', 'estranged', 'evade', 'evasion', 'evasive', 'evil', 'evildoer', 'evils', 'eviscerate', 'exacerbate', 'exagerate', 'exagerated', 'exagerates', 'exaggerate', 'exaggeration', 'exasperate', 'exasperated', 'exasperating', 'exasperatingly', 'exasperation', 'excessive', 'excessively', 'exclusion', 'excoriate', 'excruciating', 'excruciatingly', 'excuse', 'excuses', 'execrate', 'exhaust', 'exhausted', 'exhaustion', 'exhausts', 'exhorbitant', 'exhort', 'exile', 'exorbitant', 'exorbitantance', 'exorbitantly', 'expel', 'expensive', 'expire', 'expired', 'explode', 'exploit', 'exploitation', 'explosive', 'expropriate', 'expropriation', 'expulse', 'expunge', 'exterminate', 'extermination', 'extinguish', 'extort', 'extortion', 'extraneous', 'extravagance', 'extravagant', 'extravagantly', 'extremism', 'extremist', 'extremists', 'eyesore', 'f**k', 'fabricate', 'fabrication', 'facetious', 'facetiously', 'fail', 'failed', 'failing', 'fails', 'failure', 'failures', 'faint', 'fainthearted', 'faithless', 'fake', 'fall', 'fallacies', 'fallacious', 'fallaciously', 'fallaciousness', 'fallacy', 'fallen', 'falling', 'fallout', 'falls', 'false', 'falsehood', 'falsely', 'falsify', 'falter', 'faltered', 'famine', 'famished', 'fanatic', 'fanatical', 'fanatically', 'fanaticism', 'fanatics', 'fanciful', 'far-fetched', 'farce', 'farcical', 'farcical-yet-provocative', 'farcically', 'farfetched', 'fascism', 'fascist', 'fastidious', 'fastidiously', 'fastuous', 'fat', 'fat-cat', 'fat-cats', 'fatal', 'fatalistic', 'fatalistically', 'fatally', 'fatcat', 'fatcats', 'fateful', 'fatefully', 'fathomless', 'fatigue', 'fatigued', 'fatique', 'fatty', 'fatuity', 'fatuous', 'fatuously', 'fault', 'faults', 'faulty', 'fawningly', 'faze', 'fear', 'fearful', 'fearfully', 'fears', 'fearsome', 'feckless', 'feeble', 'feeblely', 'feebleminded', 'feign', 'feint', 'fell', 'felon', 'felonious', 'ferociously', 'ferocity', 'fetid', 'fever', 'feverish', 'fevers', 'fiasco', 'fib', 'fibber', 'fickle', 'fiction', 'fictional', 'fictitious', 'fidget', 'fidgety', 'fiend', 'fiendish', 'fierce', 'figurehead', 'filth', 'filthy', 'finagle', 'finicky', 'fissures', 'fist', 'flabbergast', 'flabbergasted', 'flagging', 'flagrant', 'flagrantly', 'flair', 'flairs', 'flak', 'flake', 'flakey', 'flakieness', 'flaking', 'flaky', 'flare', 'flares', 'flareup', 'flareups', 'flat-out', 'flaunt', 'flaw', 'flawed', 'flaws', 'flee', 'fleed', 'fleeing', 'fleer', 'flees', 'fleeting', 'flicering', 'flicker', 'flickering', 'flickers', 'flighty', 'flimflam', 'flimsy', 'flirt', 'flirty', 'floored', 'flounder', 'floundering', 'flout', 'fluster', 'foe', 'fool', 'fooled', 'foolhardy', 'foolish', 'foolishly', 'foolishness', 'forbid', 'forbidden', 'forbidding', 'forceful', 'foreboding', 'forebodingly', 'forfeit', 'forged', 'forgetful', 'forgetfully', 'forgetfulness', 'forlorn', 'forlornly', 'forsake', 'forsaken', 'forswear', 'foul', 'foully', 'foulness', 'fractious', 'fractiously', 'fracture', 'fragile', 'fragmented', 'frail', 'frantic', 'frantically', 'franticly', 'fraud', 'fraudulent', 'fraught', 'frazzle', 'frazzled', 'freak', 'freaking', 'freakish', 'freakishly', 'freaks', 'freeze', 'freezes', 'freezing', 'frenetic', 'frenetically', 'frenzied', 'frenzy', 'fret', 'fretful', 'frets', 'friction', 'frictions', 'fried', 'friggin', 'frigging', 'fright', 'frighten', 'frightening', 'frighteningly', 'frightful', 'frightfully', 'frigid', 'frost', 'frown', 'froze', 'frozen', 'fruitless', 'fruitlessly', 'frustrate', 'frustrated', 'frustrates', 'frustrating', 'frustratingly', 'frustration', 'frustrations', 'fuck', 'fucking', 'fudge', 'fugitive', 'full-blown', 'fulminate', 'fumble', 'fume', 'fumes', 'fundamentalism', 'funky', 'funnily', 'funny', 'furious', 'furiously', 'furor', 'fury', 'fuss', 'fussy', 'fustigate', 'fusty', 'futile', 'futilely', 'futility', 'fuzzy', 'gabble', 'gaff', 'gaffe', 'gainsay', 'gainsayer', 'gall', 'galling', 'gallingly', 'galls', 'gangster', 'gape', 'garbage', 'garish', 'gasp', 'gauche', 'gaudy', 'gawk', 'gawky', 'geezer', 'genocide', 'get-rich', 'ghastly', 'ghetto', 'ghosting', 'gibber', 'gibberish', 'gibe', 'giddy', 'gimmick', 'gimmicked', 'gimmicking', 'gimmicks', 'gimmicky', 'glare', 'glaringly', 'glib', 'glibly', 'glitch', 'glitches', 'gloatingly', 'gloom', 'gloomy', 'glower', 'glum', 'glut', 'gnawing', 'goad', 'goading', 'god-awful', 'goof', 'goofy', 'goon', 'gossip', 'graceless', 'gracelessly', 'graft', 'grainy', 'grapple', 'grate', 'grating', 'gravely', 'greasy', 'greed', 'greedy', 'grief', 'grievance', 'grievances', 'grieve', 'grieving', 'grievous', 'grievously', 'grim', 'grimace', 'grind', 'gripe', 'gripes', 'grisly', 'gritty', 'gross', 'grossly', 'grotesque', 'grouch', 'grouchy', 'groundless', 'grouse', 'growl', 'grudge', 'grudges', 'grudging', 'grudgingly', 'gruesome', 'gruesomely', 'gruff', 'grumble', 'grumpier', 'grumpiest', 'grumpily', 'grumpish', 'grumpy', 'guile', 'guilt', 'guiltily', 'guilty', 'gullible', 'gutless', 'gutter', 'hack', 'hacks', 'haggard', 'haggle', 'hairloss', 'halfhearted', 'halfheartedly', 'hallucinate', 'hallucination', 'hamper', 'hampered', 'handicapped', 'hang', 'hangs', 'haphazard', 'hapless', 'harangue', 'harass', 'harassed', 'harasses', 'harassment', 'harboring', 'harbors', 'hard', 'hard-hit', 'hard-line', 'hard-liner', 'hardball', 'harden', 'hardened', 'hardheaded', 'hardhearted', 'hardliner', 'hardliners', 'hardship', 'hardships', 'harm', 'harmed', 'harmful', 'harms', 'harpy', 'harridan', 'harried', 'harrow', 'harsh', 'harshly', 'hasseling', 'hassle', 'hassled', 'hassles', 'haste', 'hastily', 'hasty', 'hate', 'hated', 'hateful', 'hatefully', 'hatefulness', 'hater', 'haters', 'hates', 'hating', 'hatred', 'haughtily', 'haughty', 'haunt', 'haunting', 'havoc', 'hawkish', 'haywire', 'hazard', 'hazardous', 'haze', 'hazy', 'head-aches', 'headache', 'headaches', 'heartbreaker', 'heartbreaking', 'heartbreakingly', 'heartless', 'heathen', 'heavy-handed', 'heavyhearted', 'heck', 'heckle', 'heckled', 'heckles', 'hectic', 'hedge', 'hedonistic', 'heedless', 'hefty', 'hegemonism', 'hegemonistic', 'hegemony', 'heinous', 'hell', 'hell-bent', 'hellion', 'hells', 'helpless', 'helplessly', 'helplessness', 'heresy', 'heretic', 'heretical', 'hesitant', 'hestitant', 'hideous', 'hideously', 'hideousness', 'high-priced', 'hiliarious', 'hinder', 'hindrance', 'hiss', 'hissed', 'hissing', 'ho-hum', 'hoard', 'hoax', 'hobble', 'hogs', 'hollow', 'hoodium', 'hoodwink', 'hooligan', 'hopeless', 'hopelessly', 'hopelessness', 'horde', 'horrendous', 'horrendously', 'horrible', 'horrid', 'horrific', 'horrified', 'horrifies', 'horrify', 'horrifying', 'horrifys', 'hostage', 'hostile', 'hostilities', 'hostility', 'hotbeds', 'hothead', 'hotheaded', 'hothouse', 'hubris', 'huckster', 'hum', 'humid', 'humiliate', 'humiliating', 'humiliation', 'humming', 'hung', 'hurt', 'hurted', 'hurtful', 'hurting', 'hurts', 'hustler', 'hype', 'hypocricy', 'hypocrisy', 'hypocrite', 'hypocrites', 'hypocritical', 'hypocritically', 'hysteria', 'hysteric', 'hysterical', 'hysterically', 'hysterics', 'idiocies', 'idiocy', 'idiot', 'idiotic', 'idiotically', 'idiots', 'idle', 'ignoble', 'ignominious', 'ignominiously', 'ignominy', 'ignorance', 'ignorant', 'ignore', 'ill-advised', 'ill-conceived', 'ill-defined', 'ill-designed', 'ill-fated', 'ill-favored', 'ill-formed', 'ill-mannered', 'ill-natured', 'ill-sorted', 'ill-tempered', 'ill-treated', 'ill-treatment', 'ill-usage', 'ill-used', 'illegal', 'illegally', 'illegitimate', 'illicit', 'illiterate', 'illness', 'illogic', 'illogical', 'illogically', 'illusion', 'illusions', 'illusory', 'imaginary', 'imbalance', 'imbecile', 'imbroglio', 'immaterial', 'immature', 'imminence', 'imminently', 'immobilized', 'immoderate', 'immoderately', 'immodest', 'immoral', 'immorality', 'immorally', 'immovable', 'impair', 'impaired', 'impasse', 'impatience', 'impatient', 'impatiently', 'impeach', 'impedance', 'impede', 'impediment', 'impending', 'impenitent', 'imperfect', 'imperfection', 'imperfections', 'imperfectly', 'imperialist', 'imperil', 'imperious', 'imperiously', 'impermissible', 'impersonal', 'impertinent', 'impetuous', 'impetuously', 'impiety', 'impinge', 'impious', 'implacable', 'implausible', 'implausibly', 'implicate', 'implication', 'implode', 'impolite', 'impolitely', 'impolitic', 'importunate', 'importune', 'impose', 'imposers', 'imposing', 'imposition', 'impossible', 'impossiblity', 'impossibly', 'impotent', 'impoverish', 'impoverished', 'impractical', 'imprecate', 'imprecise', 'imprecisely', 'imprecision', 'imprison', 'imprisonment', 'improbability', 'improbable', 'improbably', 'improper', 'improperly', 'impropriety', 'imprudence', 'imprudent', 'impudence', 'impudent', 'impudently', 'impugn', 'impulsive', 'impulsively', 'impunity', 'impure', 'impurity', 'inability', 'inaccuracies', 'inaccuracy', 'inaccurate', 'inaccurately', 'inaction', 'inactive', 'inadequacy', 'inadequate', 'inadequately', 'inadverent', 'inadverently', 'inadvisable', 'inadvisably', 'inane', 'inanely', 'inappropriate', 'inappropriately', 'inapt', 'inaptitude', 'inarticulate', 'inattentive', 'inaudible', 'incapable', 'incapably', 'incautious', 'incendiary', 'incense', 'incessant', 'incessantly', 'incite', 'incitement', 'incivility', 'inclement', 'incognizant', 'incoherence', 'incoherent', 'incoherently', 'incommensurate', 'incomparable', 'incomparably', 'incompatability', 'incompatibility', 'incompatible', 'incompetence', 'incompetent', 'incompetently', 'incomplete', 'incompliant', 'incomprehensible', 'incomprehension', 'inconceivable', 'inconceivably', 'incongruous', 'incongruously', 'inconsequent', 'inconsequential', 'inconsequentially', 'inconsequently', 'inconsiderate', 'inconsiderately', 'inconsistence', 'inconsistencies', 'inconsistency', 'inconsistent', 'inconsolable', 'inconsolably', 'inconstant', 'inconvenience', 'inconveniently', 'incorrect', 'incorrectly', 'incorrigible', 'incorrigibly', 'incredulous', 'incredulously', 'inculcate', 'indecency', 'indecent', 'indecently', 'indecision', 'indecisive', 'indecisively', 'indecorum', 'indefensible', 'indelicate', 'indeterminable', 'indeterminably', 'indeterminate', 'indifference', 'indifferent', 'indigent', 'indignant', 'indignantly', 'indignation', 'indignity', 'indiscernible', 'indiscreet', 'indiscreetly', 'indiscretion', 'indiscriminate', 'indiscriminately', 'indiscriminating', 'indistinguishable', 'indoctrinate', 'indoctrination', 'indolent', 'indulge', 'ineffective', 'ineffectively', 'ineffectiveness', 'ineffectual', 'ineffectually', 'ineffectualness', 'inefficacious', 'inefficacy', 'inefficiency', 'inefficient', 'inefficiently', 'inelegance', 'inelegant', 'ineligible', 'ineloquent', 'ineloquently', 'inept', 'ineptitude', 'ineptly', 'inequalities', 'inequality', 'inequitable', 'inequitably', 'inequities', 'inescapable', 'inescapably', 'inessential', 'inevitable', 'inevitably', 'inexcusable', 'inexcusably', 'inexorable', 'inexorably', 'inexperience', 'inexperienced', 'inexpert', 'inexpertly', 'inexpiable', 'inexplainable', 'inextricable', 'inextricably', 'infamous', 'infamously', 'infamy', 'infected', 'infection', 'infections', 'inferior', 'inferiority', 'infernal', 'infest', 'infested', 'infidel', 'infidels', 'infiltrator', 'infiltrators', 'infirm', 'inflame', 'inflammation', 'inflammatory', 'inflammed', 'inflated', 'inflationary', 'inflexible', 'inflict', 'infraction', 'infringe', 'infringement', 'infringements', 'infuriate', 'infuriated', 'infuriating', 'infuriatingly', 'inglorious', 'ingrate', 'ingratitude', 'inhibit', 'inhibition', 'inhospitable', 'inhospitality', 'inhuman', 'inhumane', 'inhumanity', 'inimical', 'inimically', 'iniquitous', 'iniquity', 'injudicious', 'injure', 'injurious', 'injury', 'injustice', 'injustices', 'innuendo', 'inoperable', 'inopportune', 'inordinate', 'inordinately', 'insane', 'insanely', 'insanity', 'insatiable', 'insecure', 'insecurity', 'insensible', 'insensitive', 'insensitively', 'insensitivity', 'insidious', 'insidiously', 'insignificance', 'insignificant', 'insignificantly', 'insincere', 'insincerely', 'insincerity', 'insinuate', 'insinuating', 'insinuation', 'insociable', 'insolence', 'insolent', 'insolently', 'insolvent', 'insouciance', 'instability', 'instable', 'instigate', 'instigator', 'instigators', 'insubordinate', 'insubstantial', 'insubstantially', 'insufferable', 'insufferably', 'insufficiency', 'insufficient', 'insufficiently', 'insular', 'insult', 'insulted', 'insulting', 'insultingly', 'insults', 'insupportable', 'insupportably', 'insurmountable', 'insurmountably', 'insurrection', 'intefere', 'inteferes', 'intense', 'interfere', 'interference', 'interferes', 'intermittent', 'interrupt', 'interruption', 'interruptions', 'intimidate', 'intimidating', 'intimidatingly', 'intimidation', 'intolerable', 'intolerablely', 'intolerance', 'intoxicate', 'intractable', 'intransigence', 'intransigent', 'intrude', 'intrusion', 'intrusive', 'inundate', 'inundated', 'invader', 'invalid', 'invalidate', 'invalidity', 'invasive', 'invective', 'inveigle', 'invidious', 'invidiously', 'invidiousness', 'invisible', 'involuntarily', 'involuntary', 'irascible', 'irate', 'irately', 'ire', 'irk', 'irked', 'irking', 'irks', 'irksome', 'irksomely', 'irksomeness', 'irksomenesses', 'ironic', 'ironical', 'ironically', 'ironies', 'irony', 'irragularity', 'irrational', 'irrationalities', 'irrationality', 'irrationally', 'irrationals', 'irreconcilable', 'irrecoverable', 'irrecoverableness', 'irrecoverablenesses', 'irrecoverably', 'irredeemable', 'irredeemably', 'irreformable', 'irregular', 'irregularity', 'irrelevance', 'irrelevant', 'irreparable', 'irreplacible', 'irrepressible', 'irresolute', 'irresolvable', 'irresponsible', 'irresponsibly', 'irretating', 'irretrievable', 'irreversible', 'irritable', 'irritably', 'irritant', 'irritate', 'irritated', 'irritating', 'irritation', 'irritations', 'isolate', 'isolated', 'isolation', 'issue', 'issues', 'itch', 'itching', 'itchy', 'jabber', 'jaded', 'jagged', 'jam', 'jarring', 'jaundiced', 'jealous', 'jealously', 'jealousness', 'jealousy', 'jeer', 'jeering', 'jeeringly', 'jeers', 'jeopardize', 'jeopardy', 'jerk', 'jerky', 'jitter', 'jitters', 'jittery', 'job-killing', 'jobless', 'joke', 'joker', 'jolt', 'judder', 'juddering', 'judders', 'jumpy', 'junk', 'junky', 'junkyard', 'jutter', 'jutters', 'kaput', 'kill', 'killed', 'killer', 'killing', 'killjoy', 'kills', 'knave', 'knife', 'knock', 'knotted', 'kook', 'kooky', 'lack', 'lackadaisical', 'lacked', 'lackey', 'lackeys', 'lacking', 'lackluster', 'lacks', 'laconic', 'lag', 'lagged', 'lagging', 'laggy', 'lags', 'laid-off', 'lambast', 'lambaste', 'lame', 'lame-duck', 'lament', 'lamentable', 'lamentably', 'languid', 'languish', 'languor', 'languorous', 'languorously', 'lanky', 'lapse', 'lapsed', 'lapses', 'lascivious', 'last-ditch', 'latency', 'laughable', 'laughably', 'laughingstock', 'lawbreaker', 'lawbreaking', 'lawless', 'lawlessness', 'layoff', 'layoff-happy', 'lazy', 'leak', 'leakage', 'leakages', 'leaking', 'leaks', 'leaky', 'lech', 'lecher', 'lecherous', 'lechery', 'leech', 'leer', 'leery', 'left-leaning', 'lemon', 'lengthy', 'less-developed', 'lesser-known', 'letch'],
    'profanity_level': ['2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'
                        ]  
}

# 2. Convert the dataset into a pandas DataFrame
df = pd.DataFrame(data)

# 3. Preprocess the data using TF-IDF Vectorizer
# Transform words into numerical vectors using TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['word'])  # Input features (words converted to vectors)
y = df['profanity_level']  # Target variable (profanity level)

# 4. Split the data into training and testing sets (80% training, 20% testing)
# This will shuffle the data randomly and split it into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Train a Logistic Regression model on the training set
model = LogisticRegression()
model.fit(X_train, y_train)  # Train the model with the training data

# 6. Make predictions using the trained model on the testing set
y_pred = model.predict(X_test)  # Predictions on the unseen test set

# 7. Print the accuracy score
accuracy = accuracy_score(y_test, y_pred)  # Calculate accuracy of the model
print(f'Accuracy: {accuracy:.2f}')

# 8. Print the detailed classification report (precision, recall, F1-score)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 9. Print the confusion matrix (shows how the model is performing on each class)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
